site_name: PMD Core Ontology
theme: readthedocs
#theme: mkdocs
#theme: material

nav:
  - Welcome: index.md
  - Introduction to Ontologies: Introduction to Ontologies.md
  - Introduction to PMDco v3.x.x: intro.md
  - Reused Ontologies: Reused ontologies.md
  - Ontology Structure: Ontology_structure2.md
  - Patterns: patterns.md
  - PMDco User Guide: PMDco User Guide.md
  - Versions: versions.md
  - Who We Are & How to Join: Who We Are & How to Join.md
  - Publications: publications.md
  - Acknowledgements: acknowledgements.md

#nav:
#  - Welcome: index.md
#  - Introduction: intro.md
#  - Background and Context: background_and_context.md
#  - Ontology Structure: ontology_structure.md
#  - Design and Methodology: design_and_methodology.md
#  - Patterns: patterns.md
#  - Glossary and Tools: glossary_and_tools.md
#  - Versions: versions.md
#  - Contributing: contributing.md
#  - Publications: publications.md
#  - Acknowledgements: acknowledgements.md

plugins:
  - d2

